### ISSUE TITLE
Debugging grapesjs

### ISSUE THREAD

**Issue by DRoet** [GrapesJS/cli#1]
What would be the recommended way of debugging the upstream grapesjs package to see how it interacts with your plugin? You can't really add any logging since it is being pulled in using a CDN.

This is just something I've ran into when trying to debug something in the grapes-mjml plugin.

**Comment by artf** [comment]
Well, you could download the main grapesjs repo, checkout the tag for your necessary version, if requested and launch the development server on it.
Then, in your plugin project, in `_index.html`, instead of having
```html
<script src="https://unpkg.com/grapesjs"></script>
```
you'd place
```html
<script src="http://127.0.0.1:8080/dist/grapes.min.js"></script>
```

so now you can interact with grapesjs
