### ISSUE TITLE
[Feature] Install packages after create a new plugin.

### ISSUE THREAD

**Issue by ronaldohoch** [GrapesJS/cli#256]
![image](https://user-images.githubusercontent.com/2287371/126552294-fd80b707-f543-4c65-a600-2d6d717dc6c5.png)

Always, after a new plugin, i need to run `npm install`
It could be an option in the questions before create plugin, may i create a PR for it if you allow :)

**Comment by artf** [comment]
Hey @ronaldohoch sorry for the late reply, but anyway, you don't need to install anything on init (`grapesjs-cli` is the only dependency you need at the beginning and it's already installed if you're able to run `init` command). You might want to add extra packages post init, but that is your choice and is not related to the init process
