### ISSUE TITLE
Input code in build process

### ISSUE THREAD

**Issue by ronaldohoch** [GrapesJS/cli#266]
Hello Artf!

Here at my work, my web app loads all the files first at client-side, so i need to put a variable at the end of js files so the system knows it was loaded. Something like:
ControlLoading.isLoading = true;

Is there a way to edit the webpack builder of a plugin to add this while building?

**Comment by artf** [comment]
Here is explained how to customize the webpack configuration: https://github.com/artf/grapesjs-cli#customize-webpack-config
