### ISSUE TITLE
does not provide an export named 'default'

### ISSUE THREAD

**Issue by capoia** [GrapesJS/cli#278]
I'm trying to use the cli to build a plugin for my own use, copying the dist folder and trying to import it returns the error:

Uncaught SyntaxError: The requested module '/src/plugins/cubosuite-form/dist/index.js?t=1671817004952' does not provide an export named 'default'.

I'm trying to use it with vite, how would I make it use the default export?

**Comment by artf** [comment]
Hi @capoia by default, the webpack config [outputs files in `umd` format](https://github.com/artf/grapesjs-cli/blob/0b319fb62562a3444bfec7e8d1eec342c5832ebc/src/webpack.config.js#L72), in case you have to, you can [customize the webpack config](https://github.com/artf/grapesjs-cli#customize-webpack-config) (eg. by using the `module` as output)
