### ISSUE TITLE
SyntaxError: Invalid or unexpected token?

### ISSUE THREAD

**Issue by Ram-Mach** [GrapesJS/cli#284]
getting /grapesjs-my-plugin/node_modules/path-scurry/node_modules/lru-cache/dist/cjs/index.js:52
            this.signal.onabort?.(reason);
                                ^

SyntaxError: Invalid or unexpected token
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

**Comment by marktamis** [comment]
for some reason optional chaining is not working in lru-cache (I'm on nodejs 18.6.0)

As a workaround I went thru the file you mentioned to replace these - ?. and ?.) - to not make them optional and that got me through to be able to start the interactive setup

**Comment by TO-smichaelsen** [comment]
I got the same error and managed to start the init task @marktamis workaround.

Node v16.20.0
lru-cache  5.1.1

**Comment by artf** [comment]
https://github.com/GrapesJS/cli/issues/282#issuecomment-1578260790
