### ISSUE TITLE
How to configure webpack

### ISSUE THREAD

**Issue by asieraduriz** [GrapesJS/cli#4]
Hello, I have cloned your repo and I am trying to integrate a react component within the `components.js` file, just to test that I can integrate a simple functional react component.
However, I am unable to update the webpack module rules to include presets for react.

Any tips?

**Comment by asieraduriz** [comment]
In the `https://github.com/artf/grapesjs-plugin-boilerplate` deprecated repo, I am able to modify `webpack.configure.js` as I would like (in my case to add React), but in this one there's no such file to modify.

**Comment by pouyamiralayi** [comment]
@fasaas the config file you are looking for is here: ``node_modules\grapesjs-cli\src\webpack.config.js``
