### ISSUE TITLE
Ability to extend webpack config  

### ISSUE THREAD

**Issue by DRoet** [GrapesJS/cli#55]
Hi @artf, awesome project.

It would be cool to use grapesjs-cli within the `grapesjs-mjml` project, however I don't think this is currently possible since we don't have a way to extend the webpack config with additional options.

Is this something still on the roadmap? 

`@vue/cli` does something like this using webpack-merge: https://cli.vuejs.org/guide/webpack.html#simple-configuration

**Comment by artf** [comment]
You can pass additional webpack configurations via [`config`](https://github.com/artf/grapesjs-cli/blob/8095fc3245239b40e07846eaa3ae5be3af794266/src/cli.js#L16-L19) (`npx grapesjs-cli serve --config='{"prop": "value"}'`) which was the easiest way to do that but I agree that is not a valid approach for a more complex configuration. It'd be cool to let the user create a `webpack.config.js` file (which would contain an object/function) in the root of the plugin. 
I'd be glad to merge a PR for this feature 😁

**Comment by artf** [comment]
Added the possibility to use a custom `webpack.config.js`  https://github.com/artf/grapesjs-cli/releases/tag/v1.0.14
